displayName: Rewrite Body with CSP (with compression support) / test outside org

summary: A fork of Rewrite Body w/ compression support to post-process static pages and add nonces to them. Copy of joinrepublic's version to debug 5xx error

type: middleware

import: github.com/morozzzko/traefik-csp-middleware

testData:
  lastModified: true
  placeholder: DhcnhD3khTMePgXw
  monitor:
    types:
      - text/html
    methods: ["GET"]
